// eslint-disable-next-line @typescript-eslint/no-var-requires
const { faker } = require('@faker-js/faker')

module.exports = {
  async up(db) {
    return db.collection('concrete').insertMany([
      {
        category: 'concrete',
        type: 'bstgraviy',
        price: '6000',
        name: 'БСТ Гравий 5-20 М100 В7,5П4F100W2',
        description:
          'Данный бетон является тяжелым бетоном\nДанный бетон является тяжелым бетоном',
        characteristics: {
          тип: 'БСТ на гравии 5-20',
          Прочность: 'марка М100 (100 кгс/см²) и класс В7,5 (7,5 МПа).',
          Подвижность: 'П4 (высокая пластичность смеси).',
          Морозостойкость:
            'F100 (выдерживает 100 циклов замораживания-оттаивания).',
          Водонепроницаемость: 'W2 (выдерживает давление воды до 0,2 МПа).',
        },
        images: ['/img/concrete/BSTGraviy5_20M100V7,5P4F100W2.png'],
        vendorCode: faker.string.numeric(4),
        inStock: faker.string.numeric(3),
        isBestseller: faker.datatype.boolean(),
        isNew: faker.datatype.boolean(),
        popularity: +faker.string.numeric(3),
        sizes: {
          БЕЗ: true,
          ПМД5: true,
          ПМД10: true,
          ПМД15: true,
          ПМД20: true,
          ПМД25: true,
        },
      },
      {
        category: 'concrete',
        type: 'bstgraviy',
        price: '6100',
        name: 'БСТ Гравий 5-20 М150 В10П4F100W2',
        description:
          'Данный бетон является тяжелым бетоном\nДанный бетон является тяжелым бетоном',
        characteristics: {
          тип: 'БСТ на гравии 5-20',
          Прочность: 'марка М150 (150 кгс/см²) и класс В10 (10 МПа).',
          Подвижность: 'П4 (высокая пластичность смеси).',
          Морозостойкость:
            'F100 (выдерживает 100 циклов замораживания-оттаивания).',
          Водонепроницаемость: 'W2 (выдерживает давление воды до 0,2 МПа).',
        },
        images: ['/img/concrete/BSTGraviy5_20M150V10P4F100W2.png'],
        vendorCode: faker.string.numeric(4),
        inStock: faker.string.numeric(3),
        isBestseller: faker.datatype.boolean(),
        isNew: faker.datatype.boolean(),
        popularity: +faker.string.numeric(3),
        sizes: {
          БЕЗ: true,
          ПМД5: true,
          ПМД10: true,
          ПМД15: true,
          ПМД20: true,
          ПМД25: true,
        },
      },
      {
        category: 'concrete',
        type: 'bstgraviy',
        price: '6100',
        name: 'БСТ Гравий 5-20 М150 В12,5П4F100W2',
        description:
          'Данный бетон является тяжелым бетоном\nДанный бетон является тяжелым бетоном',
        characteristics: {
          тип: 'БСТ на гравии 5-20',
          Прочность: 'марка М150 (150 кгс/см²) и класс В12,5 (12,5 МПа).',
          Подвижность: 'П4 (высокая пластичность смеси).',
          Морозостойкость:
            'F100 (выдерживает 100 циклов замораживания-оттаивания).',
          Водонепроницаемость: 'W2 (выдерживает давление воды до 0,2 МПа).',
        },
        images: ['/img/concrete/BSTGraviy5_20M150V12,5P4F100W2.png'],
        vendorCode: faker.string.numeric(4),
        inStock: faker.string.numeric(3),
        isBestseller: faker.datatype.boolean(),
        isNew: faker.datatype.boolean(),
        popularity: +faker.string.numeric(3),
        sizes: {
          БЕЗ: true,
          ПМД5: true,
          ПМД10: true,
          ПМД15: true,
          ПМД20: true,
          ПМД25: true,
        },
      },
      {
        category: 'concrete',
        type: 'bstgraviy',
        price: '6200',
        name: 'БСТ Гравий 5-20 М200 В15П4F100W2',
        description:
          'Данный бетон является тяжелым бетоном\nДанный бетон является тяжелым бетоном',
        characteristics: {
          тип: 'БСТ на гравии 5-20',
          Прочность: 'марка М200 (200 кгс/см²) и класс В15 (15 МПа).',
          Подвижность: 'П4 (высокая пластичность смеси).',
          Морозостойкость:
            'F100 (выдерживает 100 циклов замораживания-оттаивания).',
          Водонепроницаемость: 'W2 (выдерживает давление воды до 0,2 МПа).',
        },
        images: ['/img/concrete/BSTGraviy5_20M200V15P4F100W2.png'],
        vendorCode: faker.string.numeric(4),
        inStock: faker.string.numeric(3),
        isBestseller: faker.datatype.boolean(),
        isNew: faker.datatype.boolean(),
        popularity: +faker.string.numeric(3),
        sizes: {
          БЕЗ: true,
          ПМД5: true,
          ПМД10: true,
          ПМД15: true,
          ПМД20: true,
          ПМД25: true,
        },
      },
      {
        category: 'concrete',
        type: 'bstgraviy',
        price: '6300',
        name: 'БСТ Гравий 5-20 М250 В20П4F100W2',
        description:
          'Данный бетон является тяжелым бетоном\nДанный бетон является тяжелым бетоном',
        characteristics: {
          тип: 'БСТ на гравии 5-20',
          Прочность: 'марка М250 (250 кгс/см²) и класс В20 (20 МПа).',
          Подвижность: 'П4 (высокая пластичность смеси).',
          Морозостойкость:
            'F100 (выдерживает 100 циклов замораживания-оттаивания).',
          Водонепроницаемость: 'W2 (выдерживает давление воды до 0,2 МПа).',
        },
        images: ['/img/concrete/BSTGraviy5_20M250V20P4F100W2.png'],
        vendorCode: faker.string.numeric(4),
        inStock: faker.string.numeric(3),
        isBestseller: faker.datatype.boolean(),
        isNew: faker.datatype.boolean(),
        popularity: +faker.string.numeric(3),
        sizes: {
          БЕЗ: true,
          ПМД5: true,
          ПМД10: true,
          ПМД15: true,
          ПМД20: true,
          ПМД25: true,
        },
      },
      {
        category: 'concrete',
        type: 'bstgraviy',
        price: '6400',
        name: 'БСТ Гравий 5-20 М300 В22,5П4F150W4',
        description:
          'Данный бетон является тяжелым бетоном\nДанный бетон является тяжелым бетоном',
        characteristics: {
          тип: 'БСТ на гравии 5-20',
          Прочность: 'марка М300 (300 кгс/см²) и класс В22,5 (22,5 МПа).',
          Подвижность: 'П4 (высокая пластичность смеси).',
          Морозостойкость:
            'F150 (выдерживает 150 циклов замораживания-оттаивания).',
          Водонепроницаемость: 'W4 (выдерживает давление воды до 0,4 МПа).',
        },
        images: ['/img/concrete/BSTGraviy5_20M300V22,5P4F150W4.png'],
        vendorCode: faker.string.numeric(4),
        inStock: faker.string.numeric(3),
        isBestseller: faker.datatype.boolean(),
        isNew: faker.datatype.boolean(),
        popularity: +faker.string.numeric(3),
        sizes: {
          БЕЗ: true,
          ПМД5: true,
          ПМД10: true,
          ПМД15: true,
          ПМД20: true,
          ПМД25: true,
        },
      },
      {
        category: 'concrete',
        type: 'bstgraviy',
        price: '6500',
        name: 'БСТ Гравий 5-20 М350 В25П4F200W8',
        description:
          'Данный бетон является тяжелым бетоном\nДанный бетон является тяжелым бетоном',
        characteristics: {
          тип: 'БСТ на гравии 5-20',
          Прочность: 'марка М350 (350 кгс/см²) и класс В25 (25 МПа).',
          Подвижность: 'П4 (высокая пластичность смеси).',
          Морозостойкость:
            'F200 (выдерживает 200 циклов замораживания-оттаивания).',
          Водонепроницаемость: 'W8 (выдерживает давление воды до 0,8 МПа).',
        },
        images: ['/img/concrete/BSTGraviy5_20M350V25P4F200W8.png'],
        vendorCode: faker.string.numeric(4),
        inStock: faker.string.numeric(3),
        isBestseller: faker.datatype.boolean(),
        isNew: faker.datatype.boolean(),
        popularity: +faker.string.numeric(3),
        sizes: {
          БЕЗ: true,
          ПМД5: true,
          ПМД10: true,
          ПМД15: true,
          ПМД20: true,
          ПМД25: true,
        },
      },
      {
        category: 'concrete',
        type: 'bstgraviy',
        price: '6800',
        name: 'БСТ Гравий 5-20 М400 В30П4F200W8',
        description:
          'Данный бетон является тяжелым бетоном\nДанный бетон является тяжелым бетоном',
        characteristics: {
          тип: 'БСТ на гравии 5-20',
          Прочность: 'марка М400 (400 кгс/см²) и класс В30 (30 МПа).',
          Подвижность: 'П4 (высокая пластичность смеси).',
          Морозостойкость:
            'F200 (выдерживает 200 циклов замораживания-оттаивания).',
          Водонепроницаемость: 'W8 (выдерживает давление воды до 0,8 МПа).',
        },
        images: ['/img/concrete/BSTGraviy5_20M400V30P4F200W8.png'],
        vendorCode: faker.string.numeric(4),
        inStock: faker.string.numeric(3),
        isBestseller: faker.datatype.boolean(),
        isNew: faker.datatype.boolean(),
        popularity: +faker.string.numeric(3),
        sizes: {
          БЕЗ: true,
          ПМД5: true,
          ПМД10: true,
          ПМД15: true,
          ПМД20: true,
          ПМД25: true,
        },
      },
      {
        category: 'concrete',
        type: 'bstgraviy',
        price: '7000',
        name: 'БСТ Гравий 5-20 М450 В35П4F200W8',
        description:
          'Данный бетон является тяжелым бетоном\nДанный бетон является тяжелым бетоном',
        characteristics: {
          тип: 'БСТ на гравии 5-20',
          Прочность: 'марка М450 (450 кгс/см²) и класс В35 (35 МПа).',
          Подвижность: 'П4 (высокая пластичность смеси).',
          Морозостойкость:
            'F200 (выдерживает 200 циклов замораживания-оттаивания).',
          Водонепроницаемость: 'W8 (выдерживает давление воды до 0,8 МПа).',
        },
        images: ['/img/concrete/BSTGraviy5_20M450V35P4F200W8.png'],
        vendorCode: faker.string.numeric(4),
        inStock: faker.string.numeric(3),
        isBestseller: faker.datatype.boolean(),
        isNew: faker.datatype.boolean(),
        popularity: +faker.string.numeric(3),
        sizes: {
          БЕЗ: true,
          ПМД5: true,
          ПМД10: true,
          ПМД15: true,
          ПМД20: true,
          ПМД25: true,
        },
      },
      {
        category: 'concrete',
        type: 'bstgraviy',
        price: '7200',
        name: 'БСТ Гравий 5-20 М550 В40П4F200W8',
        description:
          'Данный бетон является тяжелым бетоном\nДанный бетон является тяжелым бетоном',
        characteristics: {
          тип: 'БСТ на гравии 5-20',
          Прочность: 'марка М550 (550 кгс/см²) и класс В40 (40 МПа).',
          Подвижность: 'П4 (высокая пластичность смеси).',
          Морозостойкость:
            'F200 (выдерживает 200 циклов замораживания-оттаивания).',
          Водонепроницаемость: 'W8 (выдерживает давление воды до 0,8 МПа).',
        },
        images: ['/img/concrete/BSTGraviy5_20M550V40P4F200W8.png'],
        vendorCode: faker.string.numeric(4),
        inStock: faker.string.numeric(3),
        isBestseller: faker.datatype.boolean(),
        isNew: faker.datatype.boolean(),
        popularity: +faker.string.numeric(3),
        sizes: {
          БЕЗ: true,
          ПМД5: true,
          ПМД10: true,
          ПМД15: true,
          ПМД20: true,
          ПМД25: true,
        },
      },
      {
        category: 'concrete',
        type: 'bstgranit',
        price: '4900',
        name: 'БСТ Гранит 5-20 М100 В7,5П4F100W2',
        description:
          'Данный бетон является тяжелым бетоном\nДанный бетон является тяжелым бетоном',
        characteristics: {
          тип: 'БСТ на граните 5-20',
          Прочность: 'марка М100 (100 кгс/см²) и класс В7,5 (7,5 МПа).',
          Подвижность: 'П4 (высокая пластичность смеси).',
          Морозостойкость:
            'F100 (выдерживает 100 циклов замораживания-оттаивания).',
          Водонепроницаемость: 'W2 (выдерживает давление воды до 0,2 МПа).',
        },
        images: ['/img/concrete/BSTGranit5_20M100V7,5P4F100W2.png'],
        vendorCode: faker.string.numeric(4),
        inStock: faker.string.numeric(3),
        isBestseller: faker.datatype.boolean(),
        isNew: faker.datatype.boolean(),
        popularity: +faker.string.numeric(3),
        sizes: {
          БЕЗ: true,
          ПМД5: true,
          ПМД10: true,
          ПМД15: true,
          ПМД20: true,
          ПМД25: true,
        },
      },
      {
        category: 'concrete',
        type: 'bstgranit',
        price: '5000',
        name: 'БСТ Гранит 5-20 М150 В10П4F100W2',
        description:
          'Данный бетон является тяжелым бетоном\nДанный бетон является тяжелым бетоном',
        characteristics: {
          тип: 'БСТ на граните 5-20',
          Прочность: 'марка М150 (150 кгс/см²) и класс В10 (10 МПа).',
          Подвижность: 'П4 (высокая пластичность смеси).',
          Морозостойкость:
            'F100 (выдерживает 100 циклов замораживания-оттаивания).',
          Водонепроницаемость: 'W2 (выдерживает давление воды до 0,2 МПа).',
        },
        images: ['/img/concrete/BSTGranit5_20M150V10P4F100W2.png'],
        vendorCode: faker.string.numeric(4),
        inStock: faker.string.numeric(3),
        isBestseller: faker.datatype.boolean(),
        isNew: faker.datatype.boolean(),
        popularity: +faker.string.numeric(3),
        sizes: {
          БЕЗ: true,
          ПМД5: true,
          ПМД10: true,
          ПМД15: true,
          ПМД20: true,
          ПМД25: true,
        },
      },
      {
        category: 'concrete',
        type: 'bstgranit',
        price: '5000',
        name: 'БСТ Гранит 5-20 М150 В12,5П4F100W2',
        description:
          'Данный бетон является тяжелым бетоном\nДанный бетон является тяжелым бетоном',
        characteristics: {
          тип: 'БСТ на граните 5-20',
          Прочность: 'марка М150 (150 кгс/см²) и класс В12,5 (12,5 МПа).',
          Подвижность: 'П4 (высокая пластичность смеси).',
          Морозостойкость:
            'F100 (выдерживает 100 циклов замораживания-оттаивания).',
          Водонепроницаемость: 'W2 (выдерживает давление воды до 0,2 МПа).',
        },
        images: ['/img/concrete/BSTGranit5_20M150V12,5P4F100W2.png'],
        vendorCode: faker.string.numeric(4),
        inStock: faker.string.numeric(3),
        isBestseller: faker.datatype.boolean(),
        isNew: faker.datatype.boolean(),
        popularity: +faker.string.numeric(3),
        sizes: {
          БЕЗ: true,
          ПМД5: true,
          ПМД10: true,
          ПМД15: true,
          ПМД20: true,
          ПМД25: true,
        },
      },
      {
        category: 'concrete',
        type: 'bstgranit',
        price: '5100',
        name: 'БСТ Гранит 5-20 М200 В15П4F100W2',
        description:
          'Данный бетон является тяжелым бетоном\nДанный бетон является тяжелым бетоном',
        characteristics: {
          тип: 'БСТ на граните 5-20',
          Прочность: 'марка М200 (200 кгс/см²) и класс В15 (15 МПа).',
          Подвижность: 'П4 (высокая пластичность смеси).',
          Морозостойкость:
            'F100 (выдерживает 100 циклов замораживания-оттаивания).',
          Водонепроницаемость: 'W2 (выдерживает давление воды до 0,2 МПа).',
        },
        images: ['/img/concrete/BSTGranit5_20M200V15P4F100W2.png'],
        vendorCode: faker.string.numeric(4),
        inStock: faker.string.numeric(3),
        isBestseller: faker.datatype.boolean(),
        isNew: faker.datatype.boolean(),
        popularity: +faker.string.numeric(3),
        sizes: {
          БЕЗ: true,
          ПМД5: true,
          ПМД10: true,
          ПМД15: true,
          ПМД20: true,
          ПМД25: true,
        },
      },
      {
        category: 'concrete',
        type: 'bstgranit',
        price: '5200',
        name: 'БСТ Гранит 5-20 М250 В20П4F100W2',
        description:
          'Данный бетон является тяжелым бетоном\nДанный бетон является тяжелым бетоном',
        characteristics: {
          тип: 'БСТ на граните 5-20',
          Прочность: 'марка М250 (250 кгс/см²) и класс В20 (20 МПа).',
          Подвижность: 'П4 (высокая пластичность смеси).',
          Морозостойкость:
            'F100 (выдерживает 100 циклов замораживания-оттаивания).',
          Водонепроницаемость: 'W2 (выдерживает давление воды до 0,2 МПа).',
        },
        images: ['/img/concrete/BSTGranit5_20M250V20P4F100W2.png'],
        vendorCode: faker.string.numeric(4),
        inStock: faker.string.numeric(3),
        isBestseller: faker.datatype.boolean(),
        isNew: faker.datatype.boolean(),
        popularity: +faker.string.numeric(3),
        sizes: {
          БЕЗ: true,
          ПМД5: true,
          ПМД10: true,
          ПМД15: true,
          ПМД20: true,
          ПМД25: true,
        },
      },
      {
        category: 'concrete',
        type: 'bstgranit',
        price: '5300',
        name: 'БСТ Гранит 5-20 М300 В22,5П4F150W4',
        description:
          'Данный бетон является тяжелым бетоном\nДанный бетон является тяжелым бетоном',
        characteristics: {
          тип: 'БСТ на граните 5-20',
          Прочность: 'марка М300 (300 кгс/см²) и класс В22,5 (22,5 МПа).',
          Подвижность: 'П4 (высокая пластичность смеси).',
          Морозостойкость:
            'F150 (выдерживает 150 циклов замораживания-оттаивания).',
          Водонепроницаемость: 'W4 (выдерживает давление воды до 0,4 МПа).',
        },
        images: ['/img/concrete/BSTGranit5_20M300V22,5P4F150W4.png'],
        vendorCode: faker.string.numeric(4),
        inStock: faker.string.numeric(3),
        isBestseller: faker.datatype.boolean(),
        isNew: faker.datatype.boolean(),
        popularity: +faker.string.numeric(3),
        sizes: {
          БЕЗ: true,
          ПМД5: true,
          ПМД10: true,
          ПМД15: true,
          ПМД20: true,
          ПМД25: true,
        },
      },
      {
        category: 'concrete',
        type: 'bstgranit',
        price: '5400',
        name: 'БСТ Гранит 5-20 М350 В25П4F200W8',
        description:
          'Данный бетон является тяжелым бетоном\nДанный бетон является тяжелым бетоном',
        characteristics: {
          тип: 'БСТ на граните 5-20',
          Прочность: 'марка М350 (350 кгс/см²) и класс В25 (25 МПа).',
          Подвижность: 'П4 (высокая пластичность смеси).',
          Морозостойкость:
            'F200 (выдерживает 200 циклов замораживания-оттаивания).',
          Водонепроницаемость: 'W8 (выдерживает давление воды до 0,8 МПа).',
        },
        images: ['/img/concrete/BSTGranit5_20M350V25P4F200W8.png'],
        vendorCode: faker.string.numeric(4),
        inStock: faker.string.numeric(3),
        isBestseller: faker.datatype.boolean(),
        isNew: faker.datatype.boolean(),
        popularity: +faker.string.numeric(3),
        sizes: {
          БЕЗ: true,
          ПМД5: true,
          ПМД10: true,
          ПМД15: true,
          ПМД20: true,
          ПМД25: true,
        },
      },
      {
        category: 'concrete',
        type: 'bstmodif',
        price: '7800',
        name: 'БСТ Модифицированный М350 В25П5F200W16',
        description:
          'Данный бетон является тяжелым бетоном\nДанный бетон является тяжелым бетоном',
        characteristics: {
          тип: 'БСТ модифицированный',
          Прочность: 'марка М350 (350 кгс/см²) и класс В25 (25 МПа).',
          Подвижность: 'П5 (высокая пластичность смеси).',
          Морозостойкость:
            'F200 (выдерживает 200 циклов замораживания-оттаивания).',
          Водонепроницаемость: 'W16 (выдерживает давление воды до 1,6 МПа).',
        },
        images: ['/img/concrete/ModifitsirovannyyM350V25P5F200W16.png'],
        vendorCode: faker.string.numeric(4),
        inStock: faker.string.numeric(3),
        isBestseller: faker.datatype.boolean(),
        isNew: faker.datatype.boolean(),
        popularity: +faker.string.numeric(3),
        sizes: {
          БЕЗ: true,
          ПМД5: true,
          ПМД10: true,
          ПМД15: true,
          ПМД20: true,
          ПМД25: true,
        },
      },
      {
        category: 'concrete',
        type: 'bstmodif',
        price: '8100',
        name: 'БСТ Модифицированный М400 В30П5F200W16',
        description:
          'Данный бетон является тяжелым бетоном\nДанный бетон является тяжелым бетоном',
        characteristics: {
          тип: 'БСТ модифицированный',
          Прочность: 'марка М400 (400 кгс/см²) и класс В30 (30 МПа).',
          Подвижность: 'П5 (высокая пластичность смеси).',
          Морозостойкость:
            'F200 (выдерживает 200 циклов замораживания-оттаивания).',
          Водонепроницаемость: 'W16 (выдерживает давление воды до 1,6 МПа).',
        },
        images: ['/img/concrete/ModifitsirovannyyM400V30P5F200W16.png'],
        vendorCode: faker.string.numeric(4),
        inStock: faker.string.numeric(3),
        isBestseller: faker.datatype.boolean(),
        isNew: faker.datatype.boolean(),
        popularity: +faker.string.numeric(3),
        sizes: {
          БЕЗ: true,
          ПМД5: true,
          ПМД10: true,
          ПМД15: true,
          ПМД20: true,
          ПМД25: true,
        },
      },
      {
        category: 'concrete',
        type: 'bstmodif',
        price: '8400',
        name: 'БСТ Модифицированный М450 В35П5F200W18',
        description:
          'Данный бетон является тяжелым бетоном\nДанный бетон является тяжелым бетоном',
        characteristics: {
          тип: 'БСТ модифицированный',
          Прочность: 'марка М450 (450 кгс/см²) и класс В35 (35 МПа).',
          Подвижность: 'П5 (высокая пластичность смеси).',
          Морозостойкость:
            'F200 (выдерживает 200 циклов замораживания-оттаивания).',
          Водонепроницаемость: 'W18 (выдерживает давление воды до 1,8 МПа).',
        },
        images: ['/img/concrete/ModifitsirovannyyM450V35P5F200W18.png'],
        vendorCode: faker.string.numeric(4),
        inStock: faker.string.numeric(3),
        isBestseller: faker.datatype.boolean(),
        isNew: faker.datatype.boolean(),
        popularity: +faker.string.numeric(3),
        sizes: {
          БЕЗ: true,
          ПМД5: true,
          ПМД10: true,
          ПМД15: true,
          ПМД20: true,
          ПМД25: true,
        },
      },
      {
        category: 'concrete',
        type: 'bstmodif',
        price: '8700',
        name: 'БСТ Модифицированный М550 В40П5F200W18',
        description:
          'Данный бетон является тяжелым бетоном\nДанный бетон является тяжелым бетоном',
        characteristics: {
          тип: 'БСТ модифицированный',
          Прочность: 'марка М550 (550 кгс/см²) и класс В40 (40 МПа).',
          Подвижность: 'П5 (высокая пластичность смеси).',
          Морозостойкость:
            'F200 (выдерживает 200 циклов замораживания-оттаивания).',
          Водонепроницаемость: 'W18 (выдерживает давление воды до 1,8 МПа).',
        },
        images: ['/img/concrete/ModifitsirovannyyM550V40P5F200W18.png'],
        vendorCode: faker.string.numeric(4),
        inStock: faker.string.numeric(3),
        isBestseller: faker.datatype.boolean(),
        isNew: faker.datatype.boolean(),
        popularity: +faker.string.numeric(3),
        sizes: {
          БЕЗ: true,
          ПМД5: true,
          ПМД10: true,
          ПМД15: true,
          ПМД20: true,
          ПМД25: true,
        },
      },
      {
        category: 'concrete',
        type: 'dorozhnotransportniy',
        price: '7800',
        name: 'Дорожно-транспортный М350 В25П4F2300W12',
        description:
          'Данный бетон является тяжелым бетоном\nДанный бетон является тяжелым бетоном',
        characteristics: {
          тип: 'Дорожно-транспортный',
          Прочность: 'марка М350 (350 кгс/см²) и класс В25 (25 МПа).',
          Подвижность: 'П4 (высокая пластичность смеси).',
          Морозостойкость:
            'F2300 (выдерживает 2300 циклов замораживания-оттаивания).',
          Водонепроницаемость: 'W12 (выдерживает давление воды до 1,2 МПа).',
        },
        images: ['/img/concrete/Dorozhno_transportnyyM350V25P4F2300W12.png'],
        vendorCode: faker.string.numeric(4),
        inStock: faker.string.numeric(3),
        isBestseller: faker.datatype.boolean(),
        isNew: faker.datatype.boolean(),
        popularity: +faker.string.numeric(3),
        sizes: {
          БЕЗ: true,
          ПМД5: true,
          ПМД10: true,
          ПМД15: true,
          ПМД20: true,
          ПМД25: true,
        },
      },
      {
        category: 'concrete',
        type: 'dorozhnotransportniy',
        price: '8100',
        name: 'Дорожно-транспортный М400 В30П4F2300W12',
        description:
          'Данный бетон является тяжелым бетоном\nДанный бетон является тяжелым бетоном',
        characteristics: {
          тип: 'Дорожно-транспортный',
          Прочность: 'марка М400 (400 кгс/см²) и класс В30 (30 МПа).',
          Подвижность: 'П4 (высокая пластичность смеси).',
          Морозостойкость:
            'F2300 (выдерживает 2300 циклов замораживания-оттаивания).',
          Водонепроницаемость: 'W12 (выдерживает давление воды до 1,2 МПа).',
        },
        images: ['/img/concrete/Dorozhno_transportnyyM400V30P4F2300W12.png'],
        vendorCode: faker.string.numeric(4),
        inStock: faker.string.numeric(3),
        isBestseller: faker.datatype.boolean(),
        isNew: faker.datatype.boolean(),
        popularity: +faker.string.numeric(3),
        sizes: {
          БЕЗ: true,
          ПМД5: true,
          ПМД10: true,
          ПМД15: true,
          ПМД20: true,
          ПМД25: true,
        },
      },
      {
        category: 'concrete',
        type: 'dorozhnotransportniy',
        price: '8400',
        name: 'Дорожно-транспортный М450 ВЗ5П4F2300W12',
        description:
          'Данный бетон является тяжелым бетоном\nДанный бетон является тяжелым бетоном',
        characteristics: {
          тип: 'Дорожно-транспортный',
          Прочность: 'марка М450 (450 кгс/см²) и класс В35 (35 МПа).',
          Подвижность: 'П4 (высокая пластичность смеси).',
          Морозостойкость:
            'F2300 (выдерживает 2300 циклов замораживания-оттаивания).',
          Водонепроницаемость: 'W12 (выдерживает давление воды до 1,2 МПа).',
        },
        images: ['/img/concrete/Dorozhno_transportnyyM450VZ5P4F2300W12.png'],
        vendorCode: faker.string.numeric(4),
        inStock: faker.string.numeric(3),
        isBestseller: faker.datatype.boolean(),
        isNew: faker.datatype.boolean(),
        popularity: +faker.string.numeric(3),
        sizes: {
          БЕЗ: true,
          ПМД5: true,
          ПМД10: true,
          ПМД15: true,
          ПМД20: true,
          ПМД25: true,
        },
      },
      {
        category: 'concrete',
        type: 'dorozhnotransportniy',
        price: '8700',
        name: 'Дорожно-транспортный М550 В40П4F2300W12',
        description:
          'Данный бетон является тяжелым бетоном\nДанный бетон является тяжелым бетоном',
        characteristics: {
          тип: 'Дорожно-транспортный',
          Прочность: 'марка М550 (550 кгс/см²) и класс В40 (40 МПа).',
          Подвижность: 'П4 (высокая пластичность смеси).',
          Морозостойкость:
            'F2300 (выдерживает 2300 циклов замораживания-оттаивания).',
          Водонепроницаемость: 'W12 (выдерживает давление воды до 1,2 МПа).',
        },
        images: ['/img/concrete/Dorozhno_transportnyyM550V40P4FF2300W12.png'],
        vendorCode: faker.string.numeric(4),
        inStock: faker.string.numeric(3),
        isBestseller: faker.datatype.boolean(),
        isNew: faker.datatype.boolean(),
        popularity: +faker.string.numeric(3),
        sizes: {
          БЕЗ: true,
          ПМД5: true,
          ПМД10: true,
          ПМД15: true,
          ПМД20: true,
          ПМД25: true,
        },
      },
      {
        category: 'concrete',
        type: 'keramzitobeton',
        price: '6600',
        name: 'БСЛ Керамзитобетон В7,5 П4F100W2',
        description:
          'Данный бетон является тяжелым бетоном\nДанный бетон является тяжелым бетоном',
        characteristics: {
          тип: 'Керамзитобетон',
          Прочность: 'класс В7,5 (7,5 МПа).',
          Подвижность: 'П4 (высокая пластичность смеси).',
          Морозостойкость:
            'F100 (выдерживает 100 циклов замораживания-оттаивания).',
          Водонепроницаемость: 'W2 (выдерживает давление воды до 0,2 МПа).',
        },
        images: ['/img/concrete/BSLKeramzitobetonV7,5P4F100W2.png'],
        vendorCode: faker.string.numeric(4),
        inStock: faker.string.numeric(3),
        isBestseller: faker.datatype.boolean(),
        isNew: faker.datatype.boolean(),
        popularity: +faker.string.numeric(3),
        sizes: {
          БЕЗ: true,
          ПМД5: true,
          ПМД10: true,
          ПМД15: true,
          ПМД20: true,
          ПМД25: true,
        },
      },
      {
        category: 'concrete',
        type: 'rastvor',
        price: '4900',
        name: 'Раствор кладка М100',
        description:
          'Данный бетон является тяжелым бетоном\nДанный бетон является тяжелым бетоном',
        characteristics: {
          тип: 'Раствор',
          Прочность: 'марка М100 (100 кгс/см²).',
        },
        images: ['/img/concrete/RastvorkladkaМ100.png'],
        vendorCode: faker.string.numeric(4),
        inStock: faker.string.numeric(3),
        isBestseller: faker.datatype.boolean(),
        isNew: faker.datatype.boolean(),
        popularity: +faker.string.numeric(3),
        sizes: {
          БЕЗ: true,
          ПМД5: true,
          ПМД10: true,
          ПМД15: true,
          ПМД20: true,
          ПМД25: true,
        },
      },
      {
        category: 'concrete',
        type: 'rastvor',
        price: '5200',
        name: 'Раствор кладка М150',
        description:
          'Данный бетон является тяжелым бетоном\nДанный бетон является тяжелым бетоном',
        characteristics: {
          тип: 'Раствор',
          Прочность: 'марка М150 (150 кгс/см²).',
        },
        images: ['/img/concrete/RastvorkladkaМ150.png'],
        vendorCode: faker.string.numeric(4),
        inStock: faker.string.numeric(3),
        isBestseller: faker.datatype.boolean(),
        isNew: faker.datatype.boolean(),
        popularity: +faker.string.numeric(3),
        sizes: {
          БЕЗ: true,
          ПМД5: true,
          ПМД10: true,
          ПМД15: true,
          ПМД20: true,
          ПМД25: true,
        },
      },
      {
        category: 'concrete',
        type: 'rastvor',
        price: '5500',
        name: 'Раствор кладка М200',
        description:
          'Данный бетон является тяжелым бетоном\nДанный бетон является тяжелым бетоном',
        characteristics: {
          тип: 'Раствор',
          Прочность: 'марка М200 (200 кгс/см²).',
        },
        images: ['/img/concrete/RastvorkladkaМ200.png'],
        vendorCode: faker.string.numeric(4),
        inStock: faker.string.numeric(3),
        isBestseller: faker.datatype.boolean(),
        isNew: faker.datatype.boolean(),
        popularity: +faker.string.numeric(3),
        sizes: {
          БЕЗ: true,
          ПМД5: true,
          ПМД10: true,
          ПМД15: true,
          ПМД20: true,
          ПМД25: true,
        },
      },
      {
        category: 'concrete',
        type: 'rastvor',
        price: '5000',
        name: 'Раствор стяжка М100',
        description:
          'Данный бетон является тяжелым бетоном\nДанный бетон является тяжелым бетоном',
        characteristics: {
          тип: 'Раствор',
          Прочность: 'марка М100 (100 кгс/см²).',
        },
        images: ['/img/concrete/RastvorstyazhkaМ100.png'],
        vendorCode: faker.string.numeric(4),
        inStock: faker.string.numeric(3),
        isBestseller: faker.datatype.boolean(),
        isNew: faker.datatype.boolean(),
        popularity: +faker.string.numeric(3),
        sizes: {
          БЕЗ: true,
          ПМД5: true,
          ПМД10: true,
          ПМД15: true,
          ПМД20: true,
          ПМД25: true,
        },
      },
      {
        category: 'concrete',
        type: 'rastvor',
        price: '5300',
        name: 'Раствор стяжка М150',
        description:
          'Данный бетон является тяжелым бетоном\nДанный бетон является тяжелым бетоном',
        characteristics: {
          тип: 'Раствор',
          Прочность: 'марка М150 (150 кгс/см²).',
        },
        images: ['/img/concrete/RastvorstyazhkaМ150.png'],
        vendorCode: faker.string.numeric(4),
        inStock: faker.string.numeric(3),
        isBestseller: faker.datatype.boolean(),
        isNew: faker.datatype.boolean(),
        popularity: +faker.string.numeric(3),
        sizes: {
          БЕЗ: true,
          ПМД5: true,
          ПМД10: true,
          ПМД15: true,
          ПМД20: true,
          ПМД25: true,
        },
      },
      {
        category: 'concrete',
        type: 'rastvor',
        price: '5600',
        name: 'Раствор стяжка М200',
        description:
          'Данный бетон является тяжелым бетоном\nДанный бетон является тяжелым бетоном',
        characteristics: {
          тип: 'Раствор',
          Прочность: 'марка М200 (200 кгс/см²).',
        },
        images: ['/img/concrete/RastvorstyazhkaМ200.png'],
        vendorCode: faker.string.numeric(4),
        inStock: faker.string.numeric(3),
        isBestseller: faker.datatype.boolean(),
        isNew: faker.datatype.boolean(),
        popularity: +faker.string.numeric(3),
        sizes: {
          БЕЗ: true,
          ПМД5: true,
          ПМД10: true,
          ПМД15: true,
          ПМД20: true,
          ПМД25: true,
        },
      },
      {
        category: 'concrete',
        type: 'rastvor',
        price: '5200',
        name: 'Раствор модифицированный М100',
        description:
          'Данный бетон является тяжелым бетоном\nДанный бетон является тяжелым бетоном',
        characteristics: {
          тип: 'Раствор',
          Прочность: 'марка М100 (100 кгс/см²).',
        },
        images: ['/img/concrete/RastvormodifitsirovannyyМ100.png'],
        vendorCode: faker.string.numeric(4),
        inStock: faker.string.numeric(3),
        isBestseller: faker.datatype.boolean(),
        isNew: faker.datatype.boolean(),
        popularity: +faker.string.numeric(3),
        sizes: {
          БЕЗ: true,
          ПМД5: true,
          ПМД10: true,
          ПМД15: true,
          ПМД20: true,
          ПМД25: true,
        },
      },
      {
        category: 'concrete',
        type: 'rastvor',
        price: '5500',
        name: 'Раствор модифицированный М150',
        description:
          'Данный бетон является тяжелым бетоном\nДанный бетон является тяжелым бетоном',
        characteristics: {
          тип: 'Раствор',
          Прочность: 'марка М150 (150 кгс/см²).',
        },
        images: ['/img/concrete/RastvormodifitsirovannyyМ150.png'],
        vendorCode: faker.string.numeric(4),
        inStock: faker.string.numeric(3),
        isBestseller: faker.datatype.boolean(),
        isNew: faker.datatype.boolean(),
        popularity: +faker.string.numeric(3),
        sizes: {
          БЕЗ: true,
          ПМД5: true,
          ПМД10: true,
          ПМД15: true,
          ПМД20: true,
          ПМД25: true,
        },
      },
      {
        category: 'concrete',
        type: 'rastvor',
        price: '5800',
        name: 'Раствор модифицированный М200',
        description:
          'Данный бетон является тяжелым бетоном\nДанный бетон является тяжелым бетоном',
        characteristics: {
          тип: 'Раствор',
          Прочность: 'марка М200 (200 кгс/см²).',
        },
        images: ['/img/concrete/RastvormodifitsirovannyyМ200.png'],
        vendorCode: faker.string.numeric(4),
        inStock: faker.string.numeric(3),
        isBestseller: faker.datatype.boolean(),
        isNew: faker.datatype.boolean(),
        popularity: +faker.string.numeric(3),
        sizes: {
          БЕЗ: true,
          ПМД5: true,
          ПМД10: true,
          ПМД15: true,
          ПМД20: true,
          ПМД25: true,
        },
      },
    ])
  },

  async down(db) {
    return db.collection('concrete').updateMany([])
  },
}
